file:
  profile: d://uploadFiles/
spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
  thymeleaf:
    prefix: classpath:/templates/pay/
    suffix: .html
  mvc:
      static-path-pattern=/**
  resources:
            static-locations=classpath:/static/
  freemarker:
    request-context-attribute: application
    settings:
      number_format: '0.##'
    cache: false
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource #  使用druid数据源
    filters: config  # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000;config.decrpt=true;
    url: jdbc:mysql://localhost:3306/yjyj?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2b8
    username: root
    password: PJ3h+dzdr/DtksIrBoeoPNgg0I4j5bEdUVQJKHbv1qN0asIwWQW0PFyiwoaGxJfWdeTIpQCF4E0p5ZCb7PkORw==
    #java -cp druid-1.1.10.jar com.alibaba.druid.filter.config.ConfigTools you_password
    publicKey: MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBANgBJPI4eJxbj9DreXjmJTXhUMAJsWb+uuPeUoZfiqnYGiXxePhScd1O+x0TCnKXCVJPAiFxSRo419ACWjOvpSUCAwEAAQ==
    initialSize: 1                                # 初始化连接:连接池启动时创建的初始化连接数量
    minIdle: 1                                    # 最小空闲连接:连接池中容许保持空闲状态的最小连接数量,负数表示没有现在
    maxActive: 1                                 # 最大空闲连接:连接池中容许保持空闲状态的最大连接数量,超过的空闲连接将被释放,如果设置为负数表示不限制
    maxWait: 60000                                # 最大等待时间:当没有可用连接时,连接池等待连接被归还的最大时间(以毫秒计数),超过时间则抛出异常,如果设置为-1表示无限等待
    validationQuery: SELECT 1 FROM DUAL           # SQL查询,用来验证从连接池取出的连接,在将连接返回给调用者之前.如果指定,则查询必须是一个SQL SELECT并且必须返回至少一行记录
    testOnBorrow: false                           # 指明是否在从池中取出连接前进行检验,如果检验失败,则从池中去除连接并尝试取出另一个. 注意: 设置为true后如果要生效,validationQuery参数必须设置为非空字符串
    testOnReturn: false                           # 指明是否在归还到池中前进行检验
    testWhileIdle: true                           # 指明连接是否被空闲连接回收器(如果有)进行检验.如果检测失败,则连接将被从池中去除. 注意: 设置为true后如果要生效,validationQuery参数必须设置为非空字符串
    minEvictableIdleTimeMillis: 300000            # 连接在池中保持空闲而不被空闲连接回收器线程(如果有)回收的最小时间值，单位毫秒
    timeBetweenEvictionRunsMillis: 60000          # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    removeAbandoned: true                         # 是否超时关闭连接
    removeAbandonedTimeout: 1800                  # 超时时间
    poolPreparedStatements: true                  # 打开PSCache
    maxPoolPreparedStatementPerConnectionSize: 20 # 指定每个连接上PSCache的大小
    logAbandoned: true                            # 是否记录日志
  redis:
    database: 0               #  数据库索引
    hostName: 94.191.102.215    #120.92.21.162
    port: 6379
    pool:                     # 连接池配置
      max-wait-millis: 2000
      max-total: 10
    jedis:
      pool:
        min-idle: 1
        max-idle: 10
  https:     #文件上传配置大小
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
mybatis:
  mapper-locations:
    - classpath*:com/**/mapper/*.xml #mapper文件的位置
  configuration:
    jdbc-type-for-null: 'null'
    useGeneratedKeys: false
    mapUnderscoreToCamelCase: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
logging:
  level:
    root: INFO
  file: logs/dev.log
#退出登录跳转地址（如何地址是https的需要配置完整路径）
logout_success_url: /login
server:
  port: 8084